function gradu_f = invertedPendulum_gradu_f(in1,F,in3)
%INVERTEDPENDULUM_GRADU_F
%    GRADU_F = INVERTEDPENDULUM_GRADU_F(IN1,F,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    09-Jan-2020 11:59:41

I = in3(3,:);
Mc = in3(1,:);
Mp = in3(2,:);
l = in3(5,:);
th = in1(3,:);
t2 = cos(th);
t3 = Mp.^2;
t4 = l.^2;
t5 = I.*Mc.*4.0;
t6 = I.*Mp.*4.0;
t7 = Mc.*Mp.*t4;
gradu_f = [0.0,(I.*4.0+Mp.*t4)./(t5+t6+t7-t3.*t4.*cos(th.*2.0)),0.0,(Mp.*l.*t2.*-4.0)./(t5+t6+t7-t3.*t4.*(t2.^2.*2.0-1.0))];
