function gradx_f = invertedPendulum_gradx_f(in1,F,in3)
%INVERTEDPENDULUM_GRADX_F
%    GRADX_F = INVERTEDPENDULUM_GRADX_F(IN1,F,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    09-Jan-2020 11:59:41

I = in3(3,:);
Mc = in3(1,:);
Mp = in3(2,:);
b = in3(6,:);
ds = in1(2,:);
dth = in1(4,:);
g = in3(4,:);
l = in3(5,:);
th = in1(3,:);
t2 = cos(th);
t3 = sin(th);
t4 = I.*4.0;
t5 = Mp.^2;
t6 = dth.^2;
t7 = l.^2;
t8 = l.^3;
t9 = th.*2.0;
t10 = cos(t9);
t11 = sin(t9);
t12 = Mc.*t4;
t13 = Mp.*t4;
t14 = Mp.*t7;
t15 = Mc.*t14;
t16 = t4+t14;
t17 = t5.*t7.*t10;
t18 = -t17;
t19 = t12+t13+t15+t18;
t20 = 1.0./t19;
t21 = t20.^2;
gradx_f = reshape([0.0,1.0,0.0,0.0,0.0,-b.*t16.*t20,(t20.*(g.*t17.*2.0+l.*t2.*t6.*t13+t2.*t5.*t6.*t8))./2.0-t5.*t7.*t11.*t21.*(F.*t14.*2.0+F.*I.*8.0-I.*b.*ds.*8.0-b.*ds.*t14.*2.0+g.*t5.*t7.*t11+l.*t3.*t6.*t13+t3.*t5.*t6.*t8),Mp.*dth.*l.*t3.*t16.*t20,0.0,0.0,0.0,1.0,0.0,(Mp.*b.*l.*t2.*4.0)./(t12+t13+t15-t5.*t7.*(t2.^2.*2.0-1.0)),Mp.*l.*t20.*(F.*t3.*-2.0+Mc.*g.*t2+Mp.*g.*t2+b.*ds.*t3.*2.0+Mp.*l.*t6.*t10).*-2.0+Mp.^3.*t8.*t11.*t21.*(F.*t2.*2.0+Mc.*g.*t3+Mp.*g.*t3-b.*ds.*t2.*2.0+(Mp.*l.*t6.*t11)./2.0).*4.0,dth.*t5.*t7.*t11.*t20.*-2.0],[4,4]);
